name: Deploy to EC2

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 코드 체크아웃
              uses: actions/checkout@v3

            - name: Docker Hub 로그인
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker 이미지 빌드 & 푸시
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/nnouss-be:latest

            - name: EC2 배포
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd ~/nnouss-be
                      docker compose pull
                      docker compose up -d
                      docker exec nestjs-app npx prisma migrate deploy
                      docker image prune -f
